config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :create, :new] do
    resources :doses, only: [:create, :new, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:cocktail_id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1 class="text-center">- Chez Mama -</h1>
<p class="sub-title">Drink well - Live well</p>
  <div class="container">
    <div class="row justify-content-center">
      <% @cocktails.each do |cocktail| %>
        <div class="col-4 mb-3">
          <div class="card">
            <h3><%= link_to "#{cocktail.name}", cocktail_path(cocktail) %></h3>
          </div>
        </div>
        <% end %>
    </div>
  </div>
  <div class="text-center">
    <%= link_to "Add a Cocktail", new_cocktail_path, class:"btn btn-success mt-3" %>
  </div>

app/views/cocktails/new.html.erb
<div class="form-cocktail">
  <h1>Add a new cocktail 🍸</h1>

  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class:"btn btn-success" %>
  <% end %>
  <%= link_to 'Back to the cocktails', cocktails_path, class:"btn btn-info mt-3" %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <div class="cocktail-card">
    <div class="cocktail-picture">
      <% if @cocktail.photo.attached? %>
        <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
    </div>
    <div class="cocktail-ingredient">
      <h2>Ingredients</h2>
      <% @cocktail.doses.each do |dose|%>
        <p><%= dose.ingredient.name %> | <%= dose.description %> <%= link_to "Remove",
                    cocktail_dose_path(dose),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %></p>
      <% end %>
      <%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail), class:"btn btn-success" %>
    </div>
  </div>
  <%= link_to 'Back to the list', cocktails_path, class:"btn btn-info" %>
</div>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<div class="container">
  <h1>Add a new dose</h1>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit "Add a dose", class:"btn btn-success" %>
  <% end %>
  <%= link_to 'Back to the cocktail', cocktail_path(@cocktail), class:"btn btn-info mt-3" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= cl_image_path "bar_c2tyfl" %>')">
    <%= yield %>
  </body>
</html>